//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> ProductionYear { get; set; }

        // FIXME:
        public override string ToString() => 
            $"Id: {Id}, Brand: {Brand}, Model: {Model}, ProductionYear: {ProductionYear}";

        public void SetCar(int id, string brand, string model, DateTime productionYear)
        {
            Id = id;
            Brand = brand;
            Model = model;
            ProductionYear = productionYear;
            OnUpdatedInputs();
        }

        public delegate void UpdateInputsEventHandler(object source, EventArgs args);
        public event UpdateInputsEventHandler UpdatedInputs;

        protected virtual void OnUpdatedInputs()
        {
            if (UpdatedInputs != null)
            {
                UpdatedInputs(this, EventArgs.Empty);
            }
        }
    }
}
